### ISSUE TITLE
有没有兴趣在订阅页面加入 RSS 订阅地址？

### ISSUE THREAD

**Issue by bolasblack** [rpsh/letter.getpodcast.xyz#1]
我注意到你的邮件列表是用 Mailchimp 发的，Mailchimp 本身是有提供 RSS 地址的，我找了一下，你的这个邮件列表的地址是 https://us20.campaign-archive.com/feed?u=6d5c1f3e6368d6a3dad334f73&id=4117524759

我觉得或许你可以把它加入到订阅页面：

* 在页面上加一个 RSS 订阅按钮
* 在 html 里加一个 RSS 订阅的 meta 标签

**Comment by bolasblack** [comment]
对了还有，十分感谢你做的 getpodcast.xyz ，给我带来了很多便利，真的

**Comment by rpsh** [comment]
谢谢你的建议，添加上了 RSS 订阅的方法： https://letter.getpodcast.xyz/feed.xml

**Comment by bolasblack** [comment]
太棒了！谢谢！
